import type { EnterpriseRunReport, QueryCase, SourceType, TraceNode, UserRole } from '@portfolio/rag-browser-runtime'

export const CASE_LABELS: Record<string, string> = {
  supplier_relationship_001: '供应关系证据', process_flow_001: '制造工艺流程', terminology_alias_001: '行业术语归一', compound_query_001: '知识 + 实时复合查询', realtime_order_001: '订单状态 Tool', missing_constraint_001: '缺少推荐约束', no_answer_001: '无证据拒答', permission_denied_001: '权限拦截', conflicting_sources_001: '版本冲突', rewrite_fidelity_001: 'Rewrite 保真',
}
export const ROLE_LABELS: Record<UserRole, string> = { bd: 'BD / 业务拓展', operations: '集团运营', new_employee: '新员工' }
const NODE_LABELS: Record<string, string> = { normalize_query: 'Query 归一', terminology_rewrite: '术语 Rewrite', classify_intent: '分层意图识别', route_knowledge_or_realtime_data: '知识 / 实时路由', retrieve_and_rerank_or_call_business_tool: '检索重排 / Tool', generate_structured_answer: '结构化答案', citation_and_permission_check: '引用与权限检查', answer_or_refuse: '回答 / 澄清 / 拒答' }

export function QueryPanel({ cases, selected, query, role, running, onCase, onQuery, onRole, onRun }: { cases: QueryCase[]; selected: string; query: string; role: UserRole; running: boolean; onCase: (id: string) => void; onQuery: (value: string) => void; onRole: (value: UserRole) => void; onRun: () => void }) {
  return <aside className="query-panel"><header><span>QUERY DESK</span><h1>从问题开始，先决定该查什么。</h1></header><label className="field-label" htmlFor="case-select">版本化案例</label><select id="case-select" value={selected} onChange={event => onCase(event.target.value)} disabled={running}><option value="custom">自定义受控问题</option>{cases.map(item => <option key={item.case_id} value={item.case_id}>{CASE_LABELS[item.case_id]}</option>)}</select><label className="field-label">模拟用户角色</label><div className="role-switch">{(Object.keys(ROLE_LABELS) as UserRole[]).map(item => <button key={item} className={role === item ? 'active' : ''} onClick={() => onRole(item)} disabled={running}>{ROLE_LABELS[item]}</button>)}</div><label className="field-label" htmlFor="query-input">问题</label><textarea id="query-input" value={query} maxLength={500} onChange={event => onQuery(event.target.value)} disabled={running} /><div className="input-meta"><span>{[...query].length}/500</span><span>浏览器内处理 · 不保存输入</span></div><button className="run-query" onClick={onRun} disabled={running || !query.trim()}>{running ? '正在分析路由…' : '运行受控查询'}<i>↗</i></button><p className="scope-note">自定义问题只在当前术语、意图和公开语料范围内运行。超出范围会澄清或拒答。</p></aside>
}

function SourceBadge({ source }: { source: SourceType }) { const label = source === 'simulated_extension' ? '模拟扩展' : source === 'public_reconstruction' ? '公开重建' : '模拟结果'; return <span className={`source-badge ${source}`}>{label}</span> }

export function RouteMap({ report, visibleNodes }: { report: EnterpriseRunReport; visibleNodes: number }) {
  const shown = new Set(report.trace.slice(0, visibleNodes).map(item => item.node))
  return <section className="route-map"><header><span>ROUTING GRAPH</span><div><strong>{report.route.replaceAll('_', ' → ')}</strong><small>{report.intent.level_1} / {report.intent.level_2}</small></div></header><div className="query-transform"><article className={shown.has('normalize_query') ? 'ready' : ''}><span>ORIGINAL</span><p>{report.original_query}</p></article><i>→</i><article className={shown.has('terminology_rewrite') ? 'ready' : ''}><span>REWRITE</span><p>{report.rewritten_query}</p>{report.protected_constraints.length > 0 && <small>保留：{report.protected_constraints.join(' · ')}</small>}</article></div><div className={`intent-node ${shown.has('classify_intent') ? 'ready' : ''}`}><span>INTENT</span><strong>{report.intent.level_2}</strong><i>{Math.round(report.intent.confidence * 100)}%</i></div><div className="subquery-stack">{report.subqueries.map((item, index) => <article key={item}><span>Q{index + 1}</span><p>{item}</p></article>)}</div><div className={`route-fork route-${report.route}`}><article className={report.route.includes('rag') || report.route === 'version_check' ? 'selected' : ''}><span>KNOWLEDGE</span><strong>Hybrid RAG</strong><p>术语、供应关系、工艺与制度</p><SourceBadge source="public_reconstruction" /></article><div className="junction"><i /><span>{report.route === 'rag_and_tool' ? '+' : 'OR'}</span><i /></div><article className={report.route.includes('tool') ? 'selected' : ''}><span>REALTIME</span><strong>Business Tool</strong><p>询价、报价、订单与履约事实</p><SourceBadge source="simulated_extension" /></article></div><ol className="node-strip">{report.trace.map((node, index) => <li key={node.node} className={index < visibleNodes ? 'done' : ''}><i>{index < visibleNodes ? '✓' : index + 1}</i><span>{NODE_LABELS[node.node]}</span>{node.source_type === 'simulated_extension' && <b>SIM</b>}</li>)}</ol></section>
}

const RESULT_LABELS = { answer: '已回答', table: '结构化结果', clarification: '需要澄清', refusal: '无证据拒答', permission_denied: '权限已拦截' } as const
export function AnswerPanel({ report, onTrace, onDownload }: { report: EnterpriseRunReport; onTrace: () => void; onDownload: () => void }) {
  return <aside className={`answer-panel result-${report.result_type}`}><header><span>ANSWER / EVIDENCE</span><strong>{RESULT_LABELS[report.result_type]}</strong></header><section className="answer-body">{report.answer.facts.length ? report.answer.facts.map((fact, index) => <p key={fact}><span>{String(index + 1).padStart(2, '0')}</span>{fact}</p>) : <p className="closed-answer"><span>—</span>{report.answer.limitations[0]}</p>}</section>{report.answer.table.length > 0 && <div className="result-table">{report.answer.table.map((row, index) => <article key={index}>{Object.entries(row).map(([key, value]) => <div key={key}><span>{key}</span><strong>{value}</strong></div>)}</article>)}</div>}<section className="citations"><h2>证据与新鲜度</h2>{report.answer.citations.map(item => <article key={item.citation_id}><div><code>{item.citation_id}</code><strong>{item.title}</strong></div><span>{item.version_or_freshness}</span><SourceBadge source={item.source_type === 'tool' ? 'simulated_extension' : 'public_reconstruction'} /></article>)}{!report.answer.citations.length && <p>当前路径没有返回可引用证据，因此系统没有生成确定性业务结论。</p>}</section><section className="limitations"><strong>边界</strong>{report.answer.limitations.map(item => <p key={item}>{item}</p>)}</section><div className="answer-actions"><button onClick={onTrace}>查看 Trace</button><button onClick={onDownload}>下载 Run Bundle</button></div></aside>
}

export function TraceDrawer({ nodes, open, onClose }: { nodes: TraceNode[]; open: boolean; onClose: () => void }) { if (!open) return null; return <div className="trace-mask" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><aside role="dialog" aria-label="运行 Trace"><header><div><span>TRACE / SOURCE BOUNDARY</span><h2>八节点执行记录</h2></div><button onClick={onClose} aria-label="关闭 Trace">×</button></header><ol>{nodes.map(node => <li key={node.node}><i>{String(node.sequence).padStart(2, '0')}</i><div><strong>{NODE_LABELS[node.node]}</strong><code>{node.node}</code></div><SourceBadge source={node.source_type} /><small>{node.input_count} → {node.output_count} · {node.duration_ms} ms</small></li>)}</ol><p>实时 Tool 路径标记为“模拟扩展”；角色权限仅演示产品决策，不构成真实数据隔离。</p></aside></div> }
